version: "3.8"
services:
  myapp:
    container_name: react_c
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "3000:3000"

    stdin_open: true
    volumes:
      - ".:/app"
      - "/app/node_modules"
    environment:
      - CHOKIDAR_USEPOLLING=true
